services:
  - type: worker
    name: conquistas-warface-bot
    runtime: node
    plan: free
    autoDeploy: true
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: DATA_REFRESH_MINUTES
        value: 10
      - key: GITHUB_DATA_URL
        value: https://raw.githubusercontent.com/stiflerwfl1-oss/Conquistas-Warface/main/data.js
      - key: GITHUB_BRANCH
        value: main
      - key: GITHUB_DATA_PATH
        value: data.js
      - key: DISCORD_ALLOWED_CHANNEL_IDS
        value: ""
